using System.Windows;
using System.Windows.Controls;
using System.Collections.Generic;
using System.Diagnostics;
using System.Windows.Navigation;

namespace INTRA_PTZ_client
{
    public partial class RouteWindow : Window
    {
        private MainWindow mainWindow;

        private List<Route.RouteTableRow> savedRouteList = new List<Route.RouteTableRow>();

        public RouteWindow(MainWindow mainWindow)
        {
            InitializeComponent();
            this.mainWindow = mainWindow;

            this.Loaded += RouteWindow_Loaded;
            this.IsVisibleChanged += RouteWindow_IsVisibleChanged;
            this.Closing += RouteWindow_Closing;
        }

        private void RouteWindow_Loaded(object sender, RoutedEventArgs e)
        {
            //routeTable.AutoGeneratingColumn += RouteTable_AutoGeneratedColumns;
        }
        private void RouteWindow_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            savedRouteList = mainWindow.Device.Route.GetRouteList();
            routeTable.ItemsSource = mainWindow.Device.Route.GetRouteList();
        }
        private void RouteWindow_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            e.Cancel = true;
            Hide();
        }

        private void AddRowButton_Click(object sender, RoutedEventArgs e)
        {

        }

        private void DeleteRowButton_Click(object sender, RoutedEventArgs e)
        {

        }

        public void RouteTable_AutoGeneratedColumns(object s, DataGridAutoGeneratingColumnEventArgs e)
        {
            //routeTable.Columns[0].Header = "№";
        }

        private void TableMenuAddRowUp_Click(object sender, RoutedEventArgs e)
        {
            
            mainWindow.Device.Route.addrouteListUp(routeTable.SelectedIndex < 0 ? 0 : routeTable.SelectedIndex);
            routeTable.ItemsSource = mainWindow.Device.Route.GetRouteList();
        }

        private void TableMenuAddRowDown_Click(object sender, RoutedEventArgs e)
        {
            //System.Diagnostics.Trace.WriteLine(routeTable.SelectedIndex);
            mainWindow.Device.Route.addrouteListDown(routeTable.SelectedIndex < 0 ? 0 : routeTable.SelectedIndex);
            routeTable.ItemsSource = mainWindow.Device.Route.GetRouteList();
        }

        private void TableMenuDeleteRow_Click(object sender, RoutedEventArgs e)
        {
            mainWindow.Device.Route.routeListDeleteRow(routeTable.SelectedIndex);
            routeTable.ItemsSource = mainWindow.Device.Route.GetRouteList();
        }

        private void TableMenuDeleteAll_Click(object sender, RoutedEventArgs e)
        {
            mainWindow.Device.Route.routeListDeleteAll();
            routeTable.ItemsSource = mainWindow.Device.Route.GetRouteList();
        }

        private void TableMenuStartFromThisRow_Click(object sender, RoutedEventArgs e)
        {

        }

        private void RouteSaveButton_Click(object sender, RoutedEventArgs e)
        {
            routeWindow.Visibility = Visibility.Hidden;
        }
        private void RouteCancelButton_Click(object sender, RoutedEventArgs e)
        {
            mainWindow.Device.Route.SetRouteList(savedRouteList);

            routeWindow.Visibility = Visibility.Hidden;
        }

        private void Hyperlink_OpenWebConsole(object sender, RequestNavigateEventArgs e)
        {
            Process.Start(new ProcessStartInfo(/*e.Uri.AbsoluteUri*/"http://" + mainWindow.Device.Ip) { UseShellExecute = true });
            e.Handled = true;
        }
    }
}
